# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-11 03:46
from __future__ import unicode_literals

import dashboard.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_date_open', models.DateField()),
                ('acc_open_balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acc_type', models.CharField(max_length=50)),
                ('acc_curr_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('acc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bud_date', models.DateField()),
                ('bud_budgeted', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bud_outflows', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('bud_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField()),
                ('tran_payee', models.CharField(max_length=50)),
                ('tran_memo', models.CharField(blank=True, max_length=50)),
                ('tran_outflow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('tran_inflow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('tran_account', models.ForeignKey(on_delete=models.deletion.CASCADE, to='dashboard.Account')),
                ('tran_category', models.ForeignKey(on_delete=models.SET(dashboard.models.get_sentinel_category), to='dashboard.Category')),
                ('tran_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='bud_category',
            field=models.ForeignKey(on_delete=models.SET(dashboard.models.get_sentinel_category), to='dashboard.Category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='bud_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
