# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-13 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160611_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
