# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160612_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='bud_balance',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='bud_outflows',
        ),
        migrations.AlterField(
            model_name='budget',
            name='bud_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category'),
        ),
    ]
