# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-14 18:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160613_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_inflow',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_outflow',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
    ]
