# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160614_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account'),
        ),
    ]
